### ISSUE TITLE
Add mural Solutions plz

### ISSUE THREAD

**Issue by 54n5** [Keeky/keeky.github.io#4]
PlzZZZ

**Comment by Keeky** [comment]
It took quite a while to add all normal solutions. Unfortunately I don't have the time to add the murals as well. You can find solutions for them [here (M01)](http://www.gamefaqs.com/3ds/183130-pokemon-picross/faqs/72736) and [here (M02)](http://www.gamefaqs.com/3ds/183130-pokemon-picross/faqs/72737)

**Comment by 54n5** [comment]
i can help but later
